language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 7.0
- 7.1
- 7.2
matrix:
  fast_finish: true
  allow_failures:
  - php: 7.2
env:
  global:
  - APPNAME=Ffuenf_CheckoutHideShipping
  - secure: oirLJ71e03iuEtrKBGSOB0emc06+T6k/J4VfSr9BYBd5dcOGp6JDDQYDwGGZCqp6uKfZF61EXGjIMqbI6U27Y+KJFbzWnIl3vvZtELOAJuKdQxlgg9ng5PJpFRubAgTcUxgLBt6FzXqg4sBuvj+nOI72DD9IgIbNMS59WKEvR2TIxlDnwVDhPUSQQ6Xy+mCD3R1XNwWVTrYGoEdiS0AIe9IYpBgj0d8rJpDJnfoZXucUQf3Z7wGV1nbtBDulIB+VhtV194mKr/9NAan6gpFYgtZ5L/muGKWKiOBSl3QqVXT5usamwQxfn2agv2zseINsG7O1/uD8hiNY4/EhN5BvUtuqQaq0RdWXaXC/BZHuDW2Qx6vBPHVRduiMk0qH92Ee20+84d11zEz/1KuFUcMAsS6D9Eg7ZXtc+7QcW97UFTARjyCaUyByf+heqGPBJKUk7V840xrYnILHSyP/Y3MvFc1ArklQxKF/7CHhm46cskSj2fdHBeFuFp6IWw7IfWh0CMUXwNaTMQmXFZRmN/Bf9vMr/mj3KQE9+3uRyTo1r+vd5vUTbipOPBjTVIe5klkV47zDe8/McXL5Ws3Sgh3yq8czS1YR2fnAAOCaVO4mP0ShMQ2cbcb7bQ44U3tW8aDpJ6a0yCzHF6AZwpBUkr81jZ2ceeFxefMvM73IqLOoB7I=
  - secure: t/CEYN2dyBfjrU+V1qsfCCit6KiwytBsX50doNucnFpi4PEtzkD6eoj24tK1nREVqOshAPzpqssxnLFKhOG0LY0OI8TvLyudy4XaCx1qbRVAIfkjSr+chj9XrGrQSxGMFsmher9jrIxGYrEXPrvxrEiXjaz+QMk47e1ajoGjsfMpbKukh8jd5l/FbevmbDphZq1k33Wc1p/E6M0iF1y4h+tAJoBhqDemIGvmz28Bo2VrcioWY9Yw8a1M/P3xTw0jjILDDJlCHEcgvVoXd4Ww4y73iNp7fIPgxs2pBuPX6mUz58r0NKub1T/b29KIU+XK8olLOM+ECkJtaTdDDyf6HBUjQGpAWsGRE0lpLCaDdXEtIyrd41bWv7hmN+w1K++jrBpZjJH+rIvCKm8yeIx/1lzVSTEz6KX3C47Bd04bTjUjimOXfF6sTnMQL8nc5fmPmuTZBFj1ZmlAtIBzcQWheDLK0/XRP7Oz2lri3N9gFt9jt8NGem8VyvQfBgWStO3+S6uJWmaLMIOXFH3/sOx/Yg6ld2McSz+nrcF4u2jgg2Sd3nMbzbUNfv7G9si/ObTtjOHqx8IBmsEBkTRnlqFRNdPaIMrRHenToXdxmAc/kppz9yqgzEtdVlMENa68uufuxAlAm7CJ9eCKUexUCkwykUdJ9zAnz15llnbhLXe/bwY=
  - secure: uKo8bEQt3KHVRf4VMNkHxSqSytgTJjyfsYNLUlBiaSnCNAlHqJCUYgPoWUKpQE43kN71DIDltxlh9q4V/FcCaF3SziNm/ecEALzbrvbM+2RRkdC2DWl1UUuIb5JOa50CT5QQslMhiryhgW6DrCTOd6zNfSRKRhSL+LSG480IMiR6gAraQMXCE9ha/0yBziOBU1sbgGT5DQhOM3dnLgC7qd54lEieKp3DiBB+ZtZDE/wkJbLh0bsIj40zVsuRoT7Dp4QOlbrG2cna2x6PFGrz/qiYehJZgeh4922nQlTn1Ropp1maEG5+nfYxsgdTpXVsHDy5kosctMjA9u+spbgITi9YStkRD4tRMAbEKuSXUw9AhI9wmCPN5Ufpfv3Ioo1deuXKaGrQ46g80ira0B8gkvOEo5IQsUNxdSq4hc1yiQx3BU2qDmV6TLc+NShop4JY75817g6sOgCsc+bjYVXwmaAkORhST49nf0llyYlQT2UYe6DoCui3KHV9UXTlw773HKpfaI+PPujjBxrUAwnyLM2Q6Ptm7+wJ642xguZQLNZaCC/fsdN2icEQg5v2erA2EN5ZQVVOm6b/6GRPptKuKsJNBNNHD4+6kQPMQSqy3cCbN6/5QIz6gkpxKFneZdS1WeOP6b8Q+zNUrQxzfw/HiHiHSTuhvwFQoqDH960767c=
  matrix:
  - MAGENTO_VERSION=ce-1.9.3.10
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: DKcpwHhRYF82xvNf/FiY2iFm4NcFmXlNi9Nsxns/Ez5Ys/nkEqTlUdspaEkyoCycKLPh8Z7VF0k3exmDp4fVjK3fU9k+9dGJaJCzO7ur46Qbi3TuHnno8b/aQ1ZJOf3tC2ddfhci8epsnQBe/aHZL+FWA7mbGp4jFu63T1Ka84TYr9Yc+NlEOcmzYbTMI9KLl417OQZwiBqMhBX5uSB1EZEg4kPzijc0G+yPgw7UVh9Ik5QpJB2A5UpuxdqWfNtBBpTh6C4MA10e094iBax6lYLmK5jIlnb43EsDGEQr4dUl2epMosOqoFV9og/PCo5JfK1cKFNhsmYrmGlwnKVlbTK1NXz8W2fEIxuIZ9LoEDQsJlR9T+sm3uoTqlubIF+amYMiMESh0HGvmKRX2vC1kMmdF/5tWRDjEYIHcbld6ibcRKuMqgjMIU2Gy9QlSH8rudbJ+bu/sk7hXXAIQ8lQQUXz4pezENCwOwiblbZj8Fxo0aZTT7owWhwVe+2ot5Bi2fO4iGWNJ1bqdPYRjF//a0eTE0xImQTxpaZ+eLUpE5mx2uhs1JJOG6fsQywYjhZIwXhsOHWe16iZ0MBWmbo2OhLY/AviW/XTXe7kCqcJXkQ2mjexHQIl8uhpK3vq+E0r8eusHHHh/kbceHlz2eaRIV2ZM7eUzO3uONkAOFUclNs=
notifications:
  slack:
    secure: NpqpDxEFQgyPQZ2aWUiG/BgSVzVZR+xLGlAXAjYDFE+on6nVJuew5y5LF8lCxh7DlRO6m6cALX1vrfkry6LCBcnGP5X3iRfjLp4fpP3WYtmDU0ZVHwTdAiYUeKmBJdfatTYkgr4OtBhdHPCg2ihf94soNuqji/58VzXntFa2tXaz+6TNT3YyWu+mg1Uo2AVEX/f6HlIvAophmsRFXk6BUuKe9RWEjKykS0pY163OCRxp3KPwhqTzJ1Zz2Y8gyiWU6ZQbAccVW6L/D5CoLWD1ZCZeIr3uDPIrcBLZzQquZSoIC+9Owhe/Hwz2o9fJls7LhXkuEWnNqQwpgo0wZS+Cp5bpGGLiACPdvEC0CbnJgRtCrDpM0In+vvCN/gHe93UJmFIHg5qIVmu1e8/1eoEmOGrqufr/b2ckMnBBcJKhzt+9J7sYKpOXi8jzXPg9JTx0Yz2aoSFHFhBVXQWS29rqawuLOqo1aHFZY+9bdrPjzzCw9l9IzDqwRES2zb1VvUy1A5qkdn1Z9GmdCc9Pr+eNTtrl0542eN0siidp6y+c3+Olan+WAihOYklpMQ65U+srKr9kxQtbKfcCqkbktm6nrjaL10Po7iqqJyhFuFW5Df7iV0pyfEcbijNPgKJa9cPv8UkYMnjO83Sz/WvB5/PIbPr3+GXg1k51cIJZIWyTM1A=
