language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 5.5
- 5.6
- 7.0
matrix:
  fast_finish: true
  allow_failures:
  - php: 5.6
    env: MAGENTO_VERSION=ce-1.8.1.0
  - php: 7.0
    env: MAGENTO_VERSION=ce-1.8.1.0
env:
  global:
  - APPNAME=Ffuenf_CheckoutHideShipping
  - secure: tSVyTO+BFsM/2j52yOKaJf/k9ZSViPhIjpnbY+kKU6UIS5biPYdKqDShWyp6CvWXqZEYtfUHwDJHsN5lAF/RDGoE58XzUd92sz1QflHTmZwI6+wyLbQjRKWOF0d2MnD6DTziE4xEdDNDqPRvVgBFZeWXpSbvIA0Xh0FWHpx/85Brp3pOTxaDM0OiU69pQt0mCJrRfJruh+W1fn2LBR+F0VrbgP8En/6+DlZlS9A5UiZnKo2TYI8Y7re+YOunNHT2/HAkX0Mj6sH2uPnT2Unj9I80fDaZ7Ptmoc/b8dHYqm9J8hqGvK7V3HLIFIrvsHAiSMrJQRt5Xb3rYf5tUqN/uej9jTRq8l3YZjwvbDpPOdHwy2N83DgvRcjc3iOhGm+3afUfXxs0r3jF0pV9ioQ4lcp6cLotLUGLTHMJdXppk0+curex0tbHip4Mgs3Ukha1scj5bqphG0kw9LAjrpvpwOizZUmQYGMsbMBouFGhDD0YcdL3ijke0NyUN/4kAFcgXVsFZZSCnlFV658Lvq5r22oRmmZiTVsEoFPH8Xunq3RwYso7yViArTGGMIyeuZrdZvP++bkJbu+D8Qs+3OnAz0OQSZhZZ2cCsKZ4yAYKNsTQwylIY9ue+Y+bAioAeENQTIdg46MB4uF/+9N7U6V7hdi9PUkjfrAB9KewLWWdn2U=
  - secure: XKDJeiaAh/m74jsZ0PkbYVNkY4N8ekSR5zopiFRxCoT3WKowdor8zgHvNNQnCvt9z4aZLrKOw10uCQ6zYKA02Q5MaNeB5FEUVPrtmSV2nHJV+Pm8dyv9QXPp8IZr66v87YMO+Dz5L8ajutDqySddQawFBSdbr8bzBk7nYboX273ZvpqPU776X8KWFdE+m7CVtoVccnOwk0lTmhVxHMUI001sMpYtcjUSxCTzCPRk+KVgwy6tqxA8fGABcQRyI6vzb4bk0lBBu21IDV8ULleBOAetQ9dIgK2HQy3tELSw/kW475fvu9M6SpX9hMPHYguVl9uQYPb1G0TXv0vu//2NNDa1mjw8VTLFNaOtxCN/6rHmNDzC008CY7Nxomh9rODRknCk0bQ5v6wbfBuBYquD3QWO3ikYj8m4q5kb+ba3VXsY11ucBYlyX8haBHyrckuZAZ98O1Mi2RGgd9MTnFoM5zCefVgrsocwNLFIzxN/tzv4liI7VWYZAHZlpIrg8rNaPEtVaWKpqnSjePuAcddAnHX15loQEW2XMA4KxpLyLwOTDGylygwV7b7pwgN3/xpa60hDT40zBEbBCfsfQDUR4GLvVxktiRI6uOMI62MpJNNYn4l2KEXgD5GRF/RgNGV0DpYIyn+tZcFDg6XkhHrV4SfGpx6Tbgf/VOuyv+JkGGU=
  - secure: RtS7Q3cb0NwZinmFl+968G/z7CPk6M2sUQOfGfPBBm0sm0m28L2QvR/SeSz9gPpVnE2yUcnpatvd7GA9ixPXURVWZj6xHk01HMXsF778XEGvAS/LyxXs3MzncK7ShPnw5nrkpjqtNlPC8MUzc2P6x/U9N+xGp0l1CoS5mRL5UNhTgNVqUH61svKUGFjnw81Kq+MzrdtIt4R7BEzJ6oqRJCLj4U0u9mOvdOqKGageupQSdtDkUxh5m5fKprZ0E5aLvoONYJ3OFV7axXWnkVkyeb+nXR1qsVnqyRXHHOt66gvYOfc+xSu+QU2wm4aCNJGhwgCI87Pu3o812mYYPEmhsaTtEyQKmkYBXU1DdXsKhT3tQF45Y4L+ZxgE9YLROZ7tIl0R5cfPb8rfoqzwr7Rf3o6UJimQsnxwdPvVihMdFNp63yeoKoKtZOgizRXBFQmz6+Ugqp4VTEm2zI1CAfMb1SnruX7jzPME1VZsohs81yQwruTwvmo0A771fyrqHZBa7khfuhJlOsliTkC1G3Ez3xN5S2fTGB5QviLruMDtQ8xywckiPO2lTgQyg+IgrZfwoC0D1Sbq3S488XhajPRfQdcuNWSHhYb/G+xQF5RB4D5FodF+AAqNb9+cQQWezq4bQIccKMdFFRk1Ny6kEnkvN4t8rumCTlf4SqCftke8T7I=
  matrix:
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
  - MAGENTO_VERSION=ce-1.8.1.0
  - MAGENTO_VERSION=ce-1.7.0.2
  - MAGENTO_VERSION=ce-1.6.2.0
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: Ca1uL/OKb65NhTQprMNiXQW07ygsxWAkbPzCh8VRt/wqcARQau9H5VvJ4gtEslOTinYFmWiIpzW3WwS0yKGeeNDH9+rZ74A8P1a+yc7xtljaxB6Udb/Ew9jbq9mZqG9y/xy21LDx4SnPoN7qFiPpIPMtk7SmnYSG7Ool66w2VZDsAF/Ow5s0gxZLBkQ6XegXXY5ocB9CcxZjUGtR7Dr6iSQxkT66COJ2CMyd5gQVMca0VAo3Uuh1Ol0yH6/NlvCYcXNjEdPbXp0R6MxPWqHmN1tldMfGZddBXxalzCgnxx0l4LhR0JXLXbx4mfVVS8ZNAGvCug3XGV4uPK+vZ1oC7JpLY0H3QFtleLRsANrYKcql31qXsGbohWFqxvokbjiSSRyUynb/gRT1i/ycDWvt8T6+HvNIfBClUCzM9qRQnwKdOpPXvL1buPEGGpX9/jkdcycGR3DOb76F/2OIfxmD4MD2pQuRlXiFJULSngkuERlpHsiDbxTEZf4xi/2Tvvm0y/BS2lAojf2D4XSiIfmnUctxrLSaIXE5Dvwkb1R9rBJv07UPAUVIMVvn3BKAsDD8nUqaa+r8liC4oW61xU93+6i7hhlS889k/9A9mlS+PJmbayVa6VBjjiMG9tXrJOIgsecx1xeLIw5zhpKNelJltYLxXG8+xRclhPJvybiwNVY=
notifications:
  slack:
    secure: PsJuu4sVHXeVI8cIKbbHHAHQyJTCKbMJu/CF3du7L80dHF8v7vCkC8nL7hbF38NJxI+R/IMdHK+qq91OrxtV1EVEy+yHGNk5vZ9LrOYUsiaKAh8Q+4vTVlKDbtIhp4jss/lnzPWzr6H3hfwX//rQgc8E0QYt+/7hjaEhVyCJHAHEQGstMWnXAShPvlBhmbhmP+nilZRpv7tOec/2fiig4qcxp2lHPm80ghhYlOLZA31BnleU8wV0pA5reZ17Rxv0egWENr0zoc5LsJXBfpsOc2Qwy3cwIpgupn0TmslEimTQMaj9dupsrfnlwt6Wp0zuaffRCL1jUL/Cj4QdVT+n5t+guFD6Xak+6gX7egDK/kyC3YwdomZ2b7a1weCgsxpHOaqvZSdx+vLzFYQaMNH4qPkDcsRS+J1gFFWqXI9Smon6xstP2M7eTliUOhEzo3weQFI0FdW03aHBLQhK7IUrDcOrHlQnLSrvCGvbOI+Ti3SkkRihwcb7ZqCuqY+3I5aydZJMOPfbZPwIQ6eHaXW8+al3O4oFqcsZJHMuY8jDmzbQwJxpwzH+kdgP7bL/8yvm+fWb+sSLyBVQkOIfwQqMSZGDzPa2GwT6bXYFd81XyTKSQMU69AN0eSU7d7JaR4or4/EvyDPQ4/2Ee7x6RdwrbxkmnPGzunWobHqhFX7BzPs=
